class NPLAnalyzer(object):
	"""Takes in string object generated by OCR processing and analyzes
	them for key characteristics."""

	def __init__(self):
		self.setNewCharacteristics()

	def setNewCharacteristics():
		self.keyChars = {}  # sets a fresh dict of empty characteristics

	def analyze(self, segment=None):
		"""Analyzes a segment (dict) and generates key key characteristics"""
		if segment is None or not isinstance(segment, dict):
			raise TypeError("segment should be of type: dict")
